storage:
  container: "historicaldata"
  storage_account: "sgmavenmarket"

catalog: "maven_market_uc"
bronze_schema: "bronze"
silver_schema: "silver"
gold_schema: "gold"
audit_schema: "audit"

transactions:
  path: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/transactions/"
  checkpoint: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/checkpoints/transactions/"
  table: "maven_market_uc.bronze.bronze_raw_transactions"

returns:
  path: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/returns/"
  checkpoint: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/checkpoints/returns/"
  table: "maven_market_uc.bronze.bronze_raw_returns"

stores:
  path: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/stores/"
  checkpoint: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/checkpoints/stores/"
  table: "maven_market_uc.bronze.bronze_raw_stores"

regions:
  path: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/regions/"
  checkpoint: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/checkpoints/regions/"
  table: "maven_market_uc.bronze.bronze_raw_regions"

  calendar:
    path: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/calendar/"
    checkpoint: "abfss://historicaldata@sgmavenmarket.dfs.core.windows.net/checkpoints/calendar/"
    table: "maven_market_uc.bronze.bronze_raw_calendar"

kafka:
  scope: "mongo-kafka-connector"
  bootstrap_key: "kafka-bootstrap"
  api_key_name: "kafka-api-key"
  api_secret_name: "kafka-api-secret"

topics:
  orders: "orders"
  inventory: "inventory"
